### PR TITLE
Maternity-register:Allow immunization with both BCG and POLIO 0

### PR DESCRIPTION
**Pull request by semujju**
https://app.asana.com/0/1133167201254915/1170796006320345/f

### CODE REVIEW

**Comment by Mwanje** [comment]
@semujju change reference to aijar to 3.0.2-SNAPSHOT.

**Comment by Mwanje** [comment]
@semujju for this PR I thought Immunisation (BCG/POLIO 0) is to change into a checkbox instead of a radio button.

Check-box

**Comment by semujju** [comment]
> ence to aijar to 3.0.2-SNAPSHOT

Ok, thanks

**Comment by Mwanje** [comment]
@semujju check the UUID for formEncounterType it's missing a 7 at the end

**Pull request merged**
