### PR TITLE
Enable dispensing without any prescriptions

### PR DESCRIPTION
**Pull request by slubwama**
Enable Dispensing without Prescriptions
https://app.asana.com/0/1133167201254913/1160984234619921

### CODE REVIEW

**Comment by slubwama** [comment]
@solemabrothers Kindly review

**Comment by solemabrothers** [comment]
@slubwama please fix these merge conflicts

**Comment by solemabrothers** [comment]
@slubwama I am not receiving a client in the dispensing  window

**Comment by solemabrothers** [comment]
@slubwama please also resolve the conflicts

**Pull request merged**
