### PR TITLE
Mother and baby status for PNC at 6hr and 24hr

### PR DESCRIPTION
**Pull request by semujju**
https://app.asana.com/0/1133167201254915/1173418874175873/f

Immunization (BCG/POLIO ) is commented out because its concept id was overridden by (ABC/3TC) drugs. Dont merge for now.

### CODE REVIEW

**Comment by solemabrothers** [comment]
@semujju why dont we put PNC at 6 and 24 hours next to each other for easy data entry

**Comment by semujju** [comment]
> @semujju why dont we put PNC at 6 and 24 hours next to each other for easy data entry

@solemabrothers that would change the flow of events as per the paper tool.

**Comment by solemabrothers** [comment]
> 
> 
> > @semujju why dont we put PNC at 6 and 24 hours next to each other for easy data entry
> 
> @solemabrothers that would change the flow of events as per the paper tool.

@semujju this noted in that case the work is okay sofar

**Comment by semujju** [comment]
> > > @semujju why dont we put PNC at 6 and 24 hours next to each other for easy data entry
> > 
> > 
> > @solemabrothers that would change the flow of events as per the paper tool.
> 
> @semujju this noted in that case the work is okay sofar

@solemabrothers ok, thanks, will notify you when the conflicting concepts issue is resolved

**Comment by semujju** [comment]
@solemabrothers i have added the new concept for BCG/POLIO.

**Pull request merged**
