### PR TITLE
Adding Triage workflow

### PR DESCRIPTION
**Pull request by slubwama**
https://app.asana.com/0/1133167201254913/1139796124261009

### CODE REVIEW

**Comment by slubwama** [comment]
@solemabrothers for your review

**Comment by solemabrothers** [comment]
@slubwama the refer to next section is not operation. and when i save the patient, he is in both the completed and waiting ques.

**Comment by solemabrothers** [comment]
@slubwama the error we had on friday comes back on deploying these changes

**Comment by solemabrothers** [comment]
@slubwama you have added the lab module instead 
Capture

**Comment by slubwama** [comment]
@solemabrothers done with review

**Comment by solemabrothers** [comment]
@slubwama please look at the screenshots below.
refer to next sections
patient que
The same patient appears in both queues.
And the refer to next section is empty

**Comment by solemabrothers** [comment]
@slubwama please look at the Entry Point under completed queue. Its reflected under completed time.
See image attached.
patient que

**Comment by slubwama** [comment]
@solemabrothers this issue was based in patientqueueing which I resolved.

**Pull request merged**
