### PR TITLE
Adding Counsling workflows

### PR DESCRIPTION
**Pull request by slubwama**
Counseling workflow
https://app.asana.com/0/1133167201254913/1153914136237281

Adding Counseling to the worklist of clinicians
https://app.asana.com/0/1133167201254913/1153914136237282

enabling the counsellor  to see the ART Summary and the health education form for the HIV clinic
https://app.asana.com/0/1133167201254913/1153914136237284

### CODE REVIEW

**Comment by slubwama** [comment]
@solemabrothers

**Comment by solemabrothers** [comment]
@slubwama please remove the maternity, vitals and appointment folllow up forms from the counseling center session

**Comment by slubwama** [comment]
@solemabrothers Appointment followup and triage may be seen by the counsellor since according to the clinical team in some pilot sites. I will filter out  the maternity.

**Comment by slubwama** [comment]
@solemabrothers Whats the update on this

**Pull request merged**
