### PR TITLE
Implement Safe Male Circumcision Form

### PR DESCRIPTION
**Pull request by mubstimor**
### What does this PR do?
- Implements the HMIS ACP 029: Safe Male Circumcision Client Form

#### Tasks to be accomplished
- Add form fields for client information
- Add form for circumcision procedure
- Add follow up form

#### Screenshots
Screen Shot 2019-10-30 at 1 47 48 PM

### CODE REVIEW

**Comment by solemabrothers** [comment]
Add  the Encounter date on the form

**Comment by solemabrothers** [comment]
@mubstimor ensure that the calendar icon is in the field box. Please refer to this resource 
https://talk.openmrs.org/t/adding-a-calendar-image-to-html-form-entry-date-fields/6915/6

**Comment by solemabrothers** [comment]
Ensure that the Presence of AE is aligned properly

**Comment by mubstimor** [comment]
> Add the Encounter date on the form

resolved

**Comment by mubstimor** [comment]
> Ensure that the Presence of AE is aligned properly

resolved

**Pull request merged**
