### PR TITLE
Art summary page

### PR DESCRIPTION
**Pull request by semujju**
https://app.asana.com/0/1133167201254913/1169515893138985/f

### CODE REVIEW

**Review by dbaluku — COMMENTED** [review]
@semujju  here are my comments 

- keep the number of tabs the same. no need for more tabs 

- care entry point and test type info should be under same section 

- Other specify fields  for care entry point, and  ART start regimen  should be disabled by default
- lets ensure we follow the flow of the summary as on paper, keeping the tabs as they were in the previous version would guide you on the flow

- All the fields under the ART care start section should be disabled apart from thr ART Start Date,  they are only enabled when ART start date is entered

- All your add and remove row buttons in the form are broken, none is hidden 
-Please refer to the demo site to ensure that you implement the required disable and enable fields, hiding and showing on all fields as on the current form.

**Comment by semujju** [comment]
> @semujju here are my comments
> 
>     * keep the number of tabs the same. no need for more tabs
> 
>     * care entry point and test type info should be under same section
> 
>     * Other specify fields  for care entry point, and  ART start regimen  should be disabled by default
> 
>     * lets ensure we follow the flow of the summary as on paper, keeping the tabs as they were in the previous version would guide you on the flow
> 
>     * All the fields under the ART care start section should be disabled apart from thr ART Start Date,  they are only enabled when ART start date is entered
> 
>     * All your add and remove row buttons in the form are broken, none is hidden
>       -Please refer to the demo site to ensure that you implement the required disable and enable fields, hiding and showing on all fields as on the current form.

- About the tabs, they were created following the flow of the form, the old design was built basing on which sections were used most, so it kinda alters the flow though. Kindly consider looking at the paper tool again.
- The rest of the suggestions have been implemented for your review

**Comment by dbaluku** [comment]
@semujju 
A lot is still not implemented 

- Care Entry point section has only two fields, it therefore doesn't require a full section , add it just next to test type as it was already implemented

- There is unnecessary addition of tabs that is Family tracking and Periodic Screening these additional tabs can be removed if you implement the row add/remove js function as found in the current form 

- Prior ART section has a lot of blank space

**Comment by slubwama** [comment]
@semujju  resolve conflicts

**Comment by slubwama** [comment]
@semujju I don't think this PR is still is relevant.

**Pull request closed without merging**
